### ISSUE TITLE
-t <token> does not work but as a Env_variable it does.

### ISSUE THREAD

**Issue by raul1991** [BuyerQuest/vault-recursive-delete#2]
Steps to reproduce
===================

1. run the script with the following parameters
        ` ./vault-recursive-delete -p /path -t <token>`
expected : Deletion happens
actual : 403

Note: I have two tokens one that is actually on the server which does not have the permission to delete the secrets and the one that I supplied using the -t option is the root token. So I should not get 403 . Right ?

**Comment by RulerOf** [comment]
Thanks for reporting this!  It should be fixed now.
